/*
 * instructions.h
 *
 *  Created on: 10 oct. 2012
 *      Author: Paul
 */

#ifndef INSTRUCTIONS_H_
#define INSTRUCTIONS_H_

#define INS_MCS_STOP 1
#define INS_MCS_ROTATION 2
#define INS_MCS_TRANSLATION 3

#define INS_MCS_ENABLE_MOTION_CONTROL 4
#define INS_MCS_ENABLE_ROTATION 5
#define INS_MCS_ENABLE_TRANSLATION 6

#define INS_MCS_GET_ROTATION_TUNINGS 7
#define INS_MCS_SET_ROTATION_TUNINGS 8
#define INS_MCS_GET_TRANSLATION_TUNINGS 9
#define INS_MCS_SET_TRANSLATION_TUNINGS 10

#define INS_MCS_RAW_PWM 11
#define INS_MCS_SET_ORIGINAL_ANGLE 12
#define INS_MCS_GET_ANGLE 13
#define INS_MCS_GET_XY 14
#define INS_MCS_SET_XY 15
#define INS_MCS_WRITE_MEMORY 16

#endif /* INSTRUCTIONS_H_ */
